### ISSUE TITLE
Question about future releases

### ISSUE THREAD

**Issue by BradyXD** [hatninja/RetroItems#5]
Straight to the point, I just want to know if you're going to keep updating this for 1.17 or older versions like 1.12 or so.

Other than that I want to thank you for this mod I was looking for something like this for so long.

**Comment by hatninja** [comment]
I'm really glad to see there are more people like me! I've been wanting to see this for a while as well, before i gave it a shot myself. ^^  
  
To answer, i do plan to keep it updated to the latest stable version of minecraft, especially for caves & cliffs. However, supporting multiple older versions is not a skill in my repotoire yet.
